### ISSUE TITLE
Model performance issue

### ISSUE THREAD

**Issue by reasondk** [asavinov/intelligent-trading-bot#11]
@asavinov. Thanks for you sharing. Very clear. Through your code, it is found that the trained model does not perform well (precision and recall) in predicting the price decline in the future. Do you have any good suggestions?

**Comment by asavinov** [comment]
Getting good performance requires quite heavy parameterization and tuning. It is similar to other ML tasks but I would say even more difficult because there are several layers which need to be configured: finding good features, choosing relevant labels, selecting good ML algorithms and finding good hyper-parameters (which is difficult), fitting a good signal model which is responsible for turning predictions into BUY/SELL signals. In particular, I regularly change the parameters of the bot that run in Telegram to improve its performance but there is still a lot to do.
